version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: web_toz_mongo_prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: web_toz_server_prod
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
      CORS_ORIGIN: ${CORS_ORIGIN}
      LOG_LEVEL: info
      BCRYPT_ROUNDS: 12
    volumes:
      - ./server/logs:/app/logs
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web_toz_client_prod
    restart: always
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_APP_NAME: WEB TOZ PROJE 1
      REACT_APP_ENV: production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /app/node_modules
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - server
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: web_toz_nginx_prod
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - client
      - server
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge